# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'npm'
    commit-message:
      prefix: 'npm'
      include: 'scope'
    groups:
      npm-dependencies:
        patterns:
          - '*'
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'docker'
    commit-message:
      prefix: 'docker'
      include: 'scope'
    groups:
      docker-dependencies:
        patterns:
          - '*'
  - package-ecosystem: 'docker-compose'
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
      - 'docker'
    commit-message:
      prefix: 'docker-compose'
      include: 'scope'
    groups:
      docker-dependencies:
        patterns:
          - '*'
  - package-ecosystem: 'github-actions'
    directory: '/.github/workflows/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'github-actions'
      include: 'scope'
    groups:
      github-dependencies:
        patterns:
          - '*'
  - package-ecosystem: 'devcontainers'
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'devcontainers'
      include: 'scope'
    groups:
      github-dependencies:
        patterns:
          - '*'
